# Generated by Django 3.0.7 on 2020-06-27 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_auto_20200627_2047'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
