# Generated by Django 3.0.7 on 2020-06-27 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
    ]
