# Generated by Django 3.0.7 on 2020-06-28 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_user_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='token',
        ),
    ]
