# Generated by Django 3.0.7 on 2020-06-28 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_remove_user_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='postlike',
            name='value',
            field=models.IntegerField(choices=[(1, 'Up'), (-1, 'Down')], default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ResetPasswordCode',
        ),
    ]
